language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install -n

script:
  - cd tst && phpunit

after_script:
  - cd ..
  - vendor/bin/codacycoverage clover tst/log/coverage-clover.xml
  - vendor/bin/test-reporter --coverage-report tst/log/coverage-clover.xml
